POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "1984",
    "url": "https://google.com/",
    "author": "George Orwell",
    "likes": 5,
    "userId": "63f3d7684e2a7f7e0fe7e088"
}